################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint-dev = http://localhost:{{$dotenv PORT}}

### 404 landing
GET {{ endpoint-dev }}/api/landing/23423

### get all landing
GET {{ endpoint-dev }}/api/landing

### get one landing
GET {{ endpoint-dev }}/api/landing/3

### Test tableau landings
POST {{ endpoint-dev }}/api/landings
content-type: application/json

{
    "ids": [1,2,3]
}

