################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint-dev = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint-dev }}/itemm

### get all hiking
GET {{ endpoint-dev }}/api/hiking

### get one hiking
GET {{ endpoint-dev }}/api/hiking/1

### get all landing
GET {{ endpoint-dev }}/api/landing

### get one landing
GET {{ endpoint-dev }}/api/landing/1

### get all lift-off
GET {{ endpoint-dev }}/api/lift-off

### get one lift-off
GET {{ endpoint-dev }}/api/lift-off/1

### Test tableau landings
POST {{ endpoint-dev }}/api/landings
content-type: application/json

{
    "ids": [1,2,45,98]
}

### Créer un item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": "item2"
}
### Créer un mauvais item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": 2222
}
