################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint-dev = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint-dev }}/itemm

### get All hiking
GET {{ endpoint-dev }}/api/hiking

### get one hiking
GET {{ endpoint-dev }}/api/hiking/1

### Créer un item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": "item2"
}
### Créer un mauvais item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": 2222
}
