################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint-dev = http://localhost:{{$dotenv PORT}}

### 404
GET {{ endpoint-dev }}/itemm

### get all hiking
GET {{ endpoint-dev }}/api/hiking

### Post hiking for create a hiking
POST {{ endpoint-dev }}/api/hiking
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
    "name": "rando oliv5",
    "imgCard" : "https://upload.wikimedia.org/wikipedia/commons/7/78/Ch%C3%A8vre_naine_-_S%C3%A9rent_8.jpg",
    "mountain": "jura",
    "resume": "Une rando qui monte",
    "keyStage": "A/D: km 0 départ /n 1: km 3.2 tounre à gauche",
    "startingPoint": "45.88847701585252, 6.240168998430284",
    "hikingPlan" : "test",
    "positiveElevation": 1235,
    "negativeElevation": 4321,
    "overallLength": 5.5,
    "landType": "Forestier",
    "ignCardReference": "Réf 987654321",
    "hightPoint": 2543,
    "lowPoint": 1000,
    "difficulty": "Très difficile",
    "userId": 1,
    "liftOffId": 3,
    "photos": [{"name": "photo rando pourri", "url": "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"},
      {"name": "photo rando pourri2", "url": "https://www.alibabuy.com/photos/library/1500/11681.jpg"}]
}

### get one hiking
GET {{ endpoint-dev }}/api/hiking/4

### get all landing
GET {{ endpoint-dev }}/api/landing

### get one landing
GET {{ endpoint-dev }}/api/landing/2

### get all liftOff
GET {{ endpoint-dev }}/api/liftOff

### get one liftOff
GET {{ endpoint-dev }}/api/liftOff/2

### Test tableau landings
POST {{ endpoint-dev }}/api/landings
content-type: application/json

{
    "ids": [1,2,45,98]
}

### Test tableau landings heroku
POST https://apiovol.herokuapp.com/api/landings
content-type: application/json

{
    "ids": [1,2,45,98]
}

### Créer un item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": "item2"
}
### Créer un mauvais item
POST {{ endpoint-dev }}/api/item
content-type: application/json

{
    "label": 2222
}

### login
POST {{ endpoint-dev }}/api/login
content-type: application/json

{
    "user": "admin",
    "pass": "pass"
}
### bad login
POST {{ endpoint-dev }}/api/login
content-type: application/json

{
    "user": "adminnnn",
    "pass": "pass"
}

### Post a hiking : recuperer l'accessToken avant avec la route login et le copier si dessous
POST {{ endpoint-dev }}/api/hiking
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4

### Post a landing
POST {{ endpoint-dev }}/api/landing
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
      "name":"new liftOff",
      "typeOfTerrain":"new type de terrain",
      "description":"new description",
      "danger":"new danger",
      "fflvLink":"new fflvLink",
      "latitude":23.234,
      "longitude":34.23,
      "favorableWind":["O"],
      "unfavorableWind":["O"],
      "altitude":23123,
       "photos": [{"name": "photo rando pourri", "url": "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"},
      {"name": "photo rando pourri2", "url": "https://www.alibabuy.com/photos/library/1500/11681.jpg"}]
}
### Post a liftOff
POST {{ endpoint-dev }}/api/liftOff
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
      "name":"new liftOff",
      "typeOfTerrain":"new type de terrain",
      "description":"new description",
      "danger":"new danger",
      "fflvLink":"new fflvLink",
      "latitude":23.234,
      "longitude":34.23,
      "favorableWind":["O"],
      "unfavorableWind":["O"],
      "altitude":23123,
      "idLandings": [1,2],
       "photos": [{"name": "photo rando pourri", "url": "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"},
      {"name": "photo rando pourri2", "url": "https://www.alibabuy.com/photos/library/1500/11681.jpg"}]
}

### Patch hiking for modify a hiking sans modif de photo
PATCH  {{ endpoint-dev }}/api/hiking/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
    "name": "rando Renomé",
    "mountain": "Himalaya",
    "img_card" : "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"
}

### Patch hiking for modify a hiking avec modif de photo mais pas de manque d'info
PATCH  {{ endpoint-dev }}/api/hiking/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
    "name": "rando Renomé",
    "mountain": "Himalaya",
    "img_card" : "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg",
    "photo_hiking" : [{
      "id": 3,
      "title": "titre modifier OLIVIER",
      "url": "https://upload.wikimedia.org/wikipedia/commons/4/4e/La_Petite_Montagne_vue_du_Molard_de_la_Justice%2C_Jura%2C_France.jpg",
      "idHiking": 2
    },
    {
      "id": 4,
      "title": "Photo Jura 2",
      "url": "https://get.pxhere.com/photo/landscape-nature-rock-waterfall-mountain-valley-mountain-range-cliff-jungle-tourism-terrain-national-park-ridge-rocks-vegetation-poland-plateau-water-feature-ecosystem-jura-krakowsko-czestochowa-mountainous-landforms-608661.jpg",
      "idHiking": 2
    }]
}
### Patch hiking for modify a hiking avec photo mais modif partiel
PATCH  {{ endpoint-dev }}/api/hiking/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
    "name": "rando Renomé",
    "mountain": "Himalaya",
    "img_card" : "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg",
    "photo_hiking" : [{
      "id": 3,
      "titre": "title changé patch"
    }]
}