################################################################################
# Fichier de test des routes HTTP de l'API
# Nécessite l'extension REST Client pour VSCode
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################
@endpoint-dev = http://localhost:{{$dotenv PORT}}

### 404 landing
GET {{ endpoint-dev }}/api/landing/23423

### get all landing
GET {{ endpoint-dev }}/api/landing

### get one landing
GET {{ endpoint-dev }}/api/landing/35

### Test tableau landings
POST {{ endpoint-dev }}/api/landings
content-type: application/json

{
    "ids": [1,5]
}

### Test  landings
POST {{ endpoint-dev }}/api/landing/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
"name": "",
"typeOfTerrain": "ras le bonbon",
"description": "ff",
"danger": "ff",
"fflvLink": "ff",
"latitude": "50",
"longitude": "5",
"favorableWind": "O,E,ES",
"unfavorableWind": "",
"altitude": "1000",
"photo_landing": "'name': 'update photo  test2', 'url': 'https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg', 'name': 'update photo rasdfsdfndo test', 'url': 'https://idata.over-blog.com/image.jpg', 'name': 'Oliv3', 'url': 'https://idata.over-blog.com/Olivier_url.jpg'"
}


### Test  landings
POST {{ endpoint-dev }}/api/landing/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
"name": "essai1"
}

### PATCH a landing with litte information
PATCH {{ endpoint-dev }}/api/landing/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
      "name":"update liftOff",
      "typeOfTerrain":"update type de terrain",
      "description":"update description",
      "danger":"update danger",
      photo:https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg

}
### Patch landing
PATCH {{ endpoint-dev }}/api/landing/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.YWRtaW4.fuwJHQFiIlgT1krQ7dHFcldDkjwdp8-vofB_lF0VPL4
content-type: application/json

{
          "photos": [
            {"name": "update photo rando test", "url": "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"},
            {"name": "update photo rasdfsdfndo test", "url": "https://idata.over-blog.com/2/08/31/84/gifs/cockpit-avion.jpg"}
      ]
}
